name: Wangana
description:  Jekyll theme

sass:
  sass_dir: assets/css/_sass
  style: :compressed

markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "tables", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

url: https://nadjetey.github.io/wangana
permalink: /:year/:month/:title/
owner:
    name: #
    twitter: #
    github: #
    disqus_shortname: #

ga_id: #
ga_username: #

timezone: Africa/Accra